name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for Deploy through Netlify
        run: sleep 75
      - name: Cypress run
        uses: cypress-io/github-action@v2
